example.property=I AM DEV

# DataSource settings: set here your own configurations for the database
spring.datasource.url=jdbc:postgresql://database:5432/ostock_dev
spring.datasource.username=postgres
spring.datasource.password={cipher}79641b608fed780f5bc3990f2d4bcfb469dd530d440bf1216f250313a99fd5f67932a07a2c8d3526b318b61647843355