server:
  port: 8081

spring:
  application:
    name: bookservice
    profiles:
      active: dev
  main:
    web-application-type: reactive

  config:
    import: configserver:http://localhost:8888

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int(1000000)}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/