spring.datasource.url=jdbc:postgresql://localhost:5432/ostock_dev
spring.datasource.username=postgres
spring.datasource.password={cipher}79641b608fed780f5bc3990f2d4bcfb469dd530d440bf1216f250313a99fd5f67932a07a2c8d3526b318b61647843355

eureka.client.serviceUrl.defaultZone=http://localhost:8070/eureka/